name: Linux Build

on:
  release:
    types: [published]
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev libxi-dev libxcursor-dev libxrandr-dev libxinerama-dev libwayland-dev libxkbcommon-dev
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -tags opengl21 -ldflags "-s -w"

    - name: Upload build to release
      uses: Shopify/upload-to-release@v2.0.0
      with:
        name: pfinder_linux
        path: ./pfinder
        repo-token: ${{ secrets.GITHUB_TOKEN }}
      
      
    
      
